import importlib.util
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from apps import APPS
from boards import flash_catalog
from build import LINKS, PROTOCOLS
from engine import logo_mask, pack_mask
from games import GAMES
from mascots import MASCOT_CATEGORIES, MASCOTS
from themes import THEMES
from typefaces import TYPEFACES

LINK_DESC = {"ble": "Bluetooth LE, always on", "wifi": "Wi-Fi"}
PROTOCOL_DESC = {"gatt": "GATT (native)", "mqtt": "MQTT"}


def _agents():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", "..", ".."))
    path = os.path.join(repo, "hub", "src", "features", "buddy", "agents", "catalog.py")
    spec = importlib.util.spec_from_file_location("tama_agent_catalog", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return [[aid, label] for aid, label in module.AGENTS.items()]


def _default_logo(brand="gooshi"):
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", "..", ".."))
    cfg = os.path.join(repo, "brands", brand, "config.yaml")
    if not os.path.exists(cfg):
        return None
    try:
        import yaml
    except ImportError:
        return None
    with open(cfg, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    src = (data.get("brand") or {}).get("logo")
    if not src:
        return None
    w, h, rows = logo_mask(src, os.path.dirname(cfg))
    return {"w": w, "h": h, "bits": pack_mask(w, h, rows), "name": src}


def catalog():
    return {
        "boards": flash_catalog(),
        "themes": list(THEMES),
        "typefaces": [[tid, spec.get("label", tid)] for tid, spec in TYPEFACES.items()],
        "games": [[gid, meta.get("desc", gid)] for gid, meta in GAMES.items() if not meta.get("soon")],
        "apps": [[aid, meta.get("desc", aid)] for aid, meta in APPS.items()],
        "agents": _agents(),
        "packs": {name: [[mid, MASCOTS[mid]["label"]] for mid in ids]
                  for name, ids in MASCOT_CATEGORIES.items()},
        "transports": {
            "links": [[link, LINK_DESC.get(link, link)] for link in LINKS],
            "protocols": {link: [[p, PROTOCOL_DESC.get(p, p)] for p in protos]
                          for link, protos in PROTOCOLS.items()},
        },
        "logo": _default_logo(),
    }


def render(data):
    return ("// Generated by firmware/tools/generator/catalog.py -- do not edit.\n"
            "window.TAMA_CATALOG = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n")


def main(argv):
    here = os.path.dirname(os.path.abspath(__file__))
    firmware = os.path.abspath(os.path.join(here, "..", ".."))
    repo = os.path.abspath(os.path.join(firmware, ".."))
    out = argv[1] if len(argv) > 1 else os.path.join(repo, "docs", "js", "catalog.js")
    text = render(catalog())
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote catalog -> {out}")


if __name__ == "__main__":
    main(sys.argv)
