brand:
  id: chrissy
  name: TAMAGOOSHI
  mascot: JOLLY

device:
  transports:
    ble: gatt
  agent: muse
  theme:
    default: midnight
    enabled: all
  typeface:
    default: dejavu
    enabled: all
  mascot:
    default: jolly
    mood: happy
    enabled: all
  games:
    enabled: all
  apps:
    enabled: all
  persona:
    name: Chrissy
    avatar: chrissy.png
    mascot: true
