// Generated by firmware/tools/gen -- do not edit.
export default {
  "release": "https://gooshi.me/firmware/",
  "boards": [
    {
      "id": "m5stickc-plus",
      "name": "M5StickC Plus",
      "chipFamily": "ESP32",
      "asset": "m5stickcplus",
      "configOffset": 3211264
    },
    {
      "id": "m5stickc-plus-se",
      "name": "M5StickC Plus SE",
      "chipFamily": "ESP32",
      "asset": "m5stickcplusse",
      "configOffset": 3211264
    },
    {
      "id": "m5sticks3",
      "name": "M5StickS3",
      "chipFamily": "ESP32-S3",
      "asset": "m5sticks3",
      "configOffset": 6619136
    }
  ],
  "themes": [
    [
      "slate",
      "slate"
    ],
    [
      "espresso",
      "espresso"
    ],
    [
      "midnight",
      "midnight"
    ],
    [
      "timex",
      "timex"
    ],
    [
      "terra",
      "terra"
    ]
  ],
  "typefaces": [
    [
      "dejavu",
      "Smooth DejaVu"
    ],
    [
      "pixel",
      "Pixel bitmap"
    ]
  ],
  "games": [
    [
      "runner",
      "Endless dodge and jump"
    ],
    [
      "flappy",
      "Tap to flap through gaps"
    ],
    [
      "delivery",
      "Steer to drop-offs"
    ],
    [
      "scream",
      "Yell to fly (mic)"
    ],
    [
      "galaxy",
      "Tilt to dodge (IMU)"
    ],
    [
      "snake",
      "Grow the snake, avoid yourself"
    ],
    [
      "reflex",
      "Test your reaction speed"
    ],
    [
      "breakout",
      "Clear the bricks"
    ],
    [
      "balance",
      "Keep the ball on the beam"
    ],
    [
      "hush",
      "Stay quiet to sneak by"
    ],
    [
      "climb",
      "Bounce up, tilt to steer"
    ],
    [
      "simon",
      "Repeat the sequence"
    ],
    [
      "twenty48",
      "Slide tiles to 2048"
    ],
    [
      "invaders",
      "Shoot the descending grid"
    ]
  ],
  "apps": [
    [
      "clock",
      "Clock"
    ],
    [
      "stopwatch",
      "Stopwatch"
    ],
    [
      "flashlight",
      "Flashlight"
    ],
    [
      "level",
      "Spirit level"
    ],
    [
      "pomodoro",
      "Pomodoro timer"
    ],
    [
      "remote",
      "Learn & replay IR remotes"
    ],
    [
      "controller",
      "BLE gamepad for browser games"
    ],
    [
      "about",
      "Device info"
    ],
    [
      "timer",
      "Countdown timer"
    ],
    [
      "dice",
      "Roll the dice"
    ],
    [
      "coin",
      "Flip a coin"
    ],
    [
      "sound",
      "Noise level meter"
    ],
    [
      "metronome",
      "Tick at your tempo"
    ],
    [
      "media",
      "BLE media remote"
    ],
    [
      "clicker",
      "BLE presentation clicker"
    ],
    [
      "jiggler",
      "Keep the host awake"
    ],
    [
      "mouse",
      "Tilt BLE mouse"
    ],
    [
      "volume",
      "BLE volume knob"
    ],
    [
      "battery",
      "Battery level and charge"
    ],
    [
      "breath",
      "Guided breath coach"
    ]
  ],
  "agents": [
    [
      "cursor",
      "Cursor agent via cursor-sdk"
    ],
    [
      "claude",
      "Claude agent via claude-agent-sdk"
    ]
  ],
  "packs": {
    "pals": [
      [
        "cat",
        "mochi"
      ],
      [
        "dog",
        "shiba"
      ],
      [
        "duck",
        "ducky"
      ]
    ],
    "trucks": [
      [
        "hauler",
        "hauler"
      ],
      [
        "towie",
        "towie"
      ],
      [
        "parcel",
        "parcel"
      ]
    ],
    "poke": [
      [
        "eevee",
        "eevee"
      ],
      [
        "squirtle",
        "squirtle"
      ],
      [
        "bulbasaur",
        "bulba"
      ]
    ],
    "claude": [
      [
        "clawd",
        "clawd"
      ]
    ]
  },
  "transports": {
    "links": [
      [
        "ble",
        "Bluetooth LE, always on"
      ],
      [
        "wifi",
        "Wi-Fi"
      ]
    ],
    "protocols": {
      "ble": [
        [
          "gatt",
          "GATT (native)"
        ]
      ],
      "wifi": [
        [
          "mqtt",
          "MQTT"
        ]
      ]
    }
  },
  "hid_modes": [
    [
      "gamepad",
      "Gamepad",
      [
        "gamepad"
      ]
    ],
    [
      "desk",
      "Desk",
      [
        "media",
        "keyboard",
        "mouse"
      ]
    ],
    [
      "off",
      "Off",
      []
    ]
  ],
  "logo": {
    "w": 24,
    "h": 24,
    "bits": "001800003c00003c000c3c301e3c781f3cf80f99f00781e00300c00000007c183efe3c7ffe3c7f7c183e0000000300c00781e00f99f01f3cf81e3c780c3c30003c00003c00001800",
    "name": "logo.png"
  }
};
